version: '3.2'
services:
  cron:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env

  redis:
    image: redis:4.0.8
    ports:
      - 6379:6379
    volumes:
      - /tmp/redis:/data
